insert into FOOD_ITEM (id, name, flavour, quantity, price) values (1, 'sandwich', 'veggie delight', 96, '7.69');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (2, 'burrito', 'grilled chicken', 19, '9.54');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (3, 'pasta', 'tuna', 29, '2.99');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (4, 'wrap', 'veggie delight', 56, '13.29');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (5, 'pizza', 'pepperoni', 42, '14.36');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (6, 'soup', 'beef and potato', 14, '11.46');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (7, 'soup', 'vegetable', 51, '12.70');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (8, 'salad', 'caesar', 61, '1.91');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (9, 'pasta', 'tomato', 77, '1.99');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (10, 'burger', 'beef', 47, '10.81');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (11, 'salad', 'veggie delight', 93, '12.81');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (12, 'burger', 'turkey club', 2, '6.75');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (13, 'soup', 'BBQ pulled pork', 60, '5.52');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (14, 'pizza', 'BBQ pulled pork', 72, '5.35');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (15, 'taco', 'bacon avocado', 74, '10.59');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (16, 'wrap', 'ham and cheese', 59, '14.26');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (17, 'taco', 'grilled chicken', 80, '3.60');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (18, 'wrap', 'turkey club', 18, '14.71');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (19, 'burrito', 'BBQ pulled pork', 11, '2.22');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (20, 'pasta', 'veggie delight', 9, '6.62');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (21, 'pasta', 'turkey club', 41, '12.59');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (22, 'burger', 'veggie delight', 19, '3.37');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (23, 'sushi', 'BBQ pulled pork', 45, '1.18');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (24, 'taco', 'grilled chicken', 40, '12.89');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (25, 'soup', 'fish', 28, '7.57');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (26, 'soup', 'grilled chicken', 39, '2.97');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (27, 'pasta', 'grilled chicken', 78, '10.90');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (28, 'burger', 'bacon and cheese', 34, '10.05');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (29, 'soup', 'bacon avocado', 74, '1.69');
insert into FOOD_ITEM (id, name, flavour, quantity, price) values (30, 'sandwich', 'turkey club', 57, '4.93');
commit;